# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 1 * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: Spark61
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Europe/Berlin
          plugin_contributors: yes
          plugin_contributors_head: master
          plugin_contributors_ignored: github-actions[bot], dependabot[bot], dependabot-preview[bot]
          plugin_licenses: yes
          plugin_licenses_legal: yes
